<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\AslSu.Application\AslSu.Application.csproj" />
    <ProjectReference Include="..\AslSu.Infrastructure\AslSu.Infrastructure.csproj" />
    <ProjectReference Include="..\AslSu.TrendyolGo\AslSu.TrendyolGo.csproj" />
  </ItemGroup>

</Project>
